# Generated by Django 4.0.4 on 2022-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vend_code', models.CharField(max_length=50, verbose_name='Артикул')),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
